// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package testdb

import (
	"database/sql"
)

type Product struct {
	ProductNo int32
	Name      string
	Price     int32
}

type User struct {
	UserID    string
	UserName  string
	CreatedAt sql.NullTime
}
